services:
  database:
    image: postgres:17-alpine
    container_name: todo_app_postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # сохрани данные в томе под именем postgres_data и внутреннему адресу в контейнера
      # uncomment if you want to persist PG data
      # - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: todo_app_container
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - .env
    environment:
      DB__URL: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}"


# перечисление томов используемых выше. если нет настроек, ставятся по умолчанию
volumes:
  postgres_data:
