apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-app-deployment
  name: todo-app-deployment
  namespace: todo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: todo-app-deployment
    spec:
      containers:
      - image: todo-fastapi:1.0.0
        name: todo-app
        resources: {}

        # --- НАСТРОЙКА РЕСУРСОВ И ЛИМИТОВ ---
        resources:
          requests:
            cpu: "100m"             # 10% от одного ядра CPU
            memory: "128Mi"         # 128 Мегабайт оперативной памяти
          limits:
            cpu: "500m"             # половина ядра
            memory: "256Mi"         # потолок RAM, при превышении — OOMKilled

        # --- НАСТРОЙКА LIVENESS PROBE (ЖИВУЧЕСТЬ) ---
        # проверка что приложение доступно
        livenessProbe:
          httpGet:
            path: /healthcheck/live      # эндпоинт из FastAPI
            port: 8000              # Порт приложения
          initialDelaySeconds: 10   # ждать 10 сек после старта
          periodSeconds: 30         # проверка каждые 30 секунд
          timeoutSeconds: 5         # не ответило за 5 сек = проверка провалена
          failureThreshold: 3       # после 3 неудач, K8s перезапустит Под

        # --- НАСТРОЙКА READINESS PROBE (ГОТОВНОСТЬ К ТРАФИКУ) ---
        # проверка что база доступна
        readinessProbe:
          httpGet:
            path: /healthcheck/ready      # эндпоинт на готовность к БД
            port: 8000
          initialDelaySeconds: 12    # Первая проверка через 12 сек
          periodSeconds: 10         # проверки каждые 10 сек
          timeoutSeconds: 3         # Время ожидания ответа — 3 секунды
          failureThreshold: 3       # Если 3 раза упало — убираем Под из маршрутизации Сервиса
        # ПОДГРУЖАЕМ ПЕРЕМЕННЫЕ ИЗ .ENV
        envFrom:
        - configMapRef:
            name: todo-env-config
        # ПЕРЕОПРЕДЕЛЕНИЕ ВНУТРИ КУБЕРА
        env:
        - name: DB__URL
          value: "postgresql+asyncpg://brutn:brutn@todo-postgres-service:5432/todo_app_db"
        # КУДА ВНУТРИ КОНТЕЙНЕРА ПОЛОЖИТЬ КЛЮЧИ
        volumeMounts:
        - name: certs-volume
          mountPath: /app/certs
          readOnly: true
      # ИСТОЧНИК ДЛЯ ПАПКИ
      volumes:
      - name: certs-volume
        secret:
         secretName: todo-certs-secret
status: {}
