apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-app-deployment
  name: todo-app-deployment
  namespace: todo-app
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: todo-app-deployment
  type: NodePort
status:
  loadBalancer: {}
