"""init_db_with_username

Revision ID: 44e040597163
Revises:
Create Date: 2026-08-16 18:53:30.020589

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '44e040597163'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('hashed_password', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('username')
    )
    op.create_table('lists',
    sa.Column('id_list', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id_user'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_list')
    )
    op.create_table('tasks',
    sa.Column('id_task', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=64), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id_list'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_task')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('lists')
    op.drop_table('users')
    # ### end Alembic commands ###
