name: CI Quality Gate

on:
  push:
    branches:
      - '**' # Запуск при любом пуше в любую ветку
  pull_request:
    branches: [ main ] # Запуск при создании PR в ветку main

jobs:

  # Джоб: клонирование кода, установка uv, установка зависимостей, запуск линтера (без исправлений)
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone code to runner
        uses: actions/checkout@v5

      - name: Install uv tool
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run Linter
        run: make lint

  # Джоб: подготовка окружения и ключей (артефактов)
  prepare-artifacts:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Generate dummy public JWT key for testing
        run: |
          mkdir -p certs
          openssl genpkey -algorithm RSA -out certs/jwt-private-key.pem -pkeyopt rsa_keygen_bits:2048
          openssl rsa -pubout -in certs/jwt-private-key.pem -out certs/jwt-public-key.pem
          
          # Создаем фейковый .env для Docker Compose
          echo "POSTGRES_USER=test_user" >> .env
          echo "POSTGRES_PASSWORD=test_password" >> .env
          echo "POSTGRES_DB=test_db" >> .env

      # сохранить ключи и .env как артефакты, чтобы передать в следующие job
      - name: Upload generated certs and env
        uses: actions/upload-artifact@v7
        with:
          name: ci-test-artifacts
          path: |
            certs/
            .env
          retention-days: 1

  # Джоб: клонирование кода, загрузка артефактов, установка uv, установка зависимостей, запуск юнит и апи тестов
  unit-and-api-tests:
    runs-on: ubuntu-latest
    needs: prepare-artifacts
    steps:
      - name: Clone code to runner
        uses: actions/checkout@v5

      # загрузка созданных раннее артефактов для работы с ними
      - name: Download generated certs and env
        uses: actions/download-artifact@v7
        with:
          name: ci-test-artifacts

        # перенос аортефактов в корень проекта
      - name: Move artifacts to root
        run: |
          cp -r ci-test-artifacts/.env ci-test-artifacts/certs .
          rm -rf ci-test-artifacts

      - name: Install uv tool
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run unit and api tests
        run: |
          make test-crud
          make test-auth
          make test-api

  # Джоб: итоговые тесты Е2Е
  e2e_tests:
    runs-on: ubuntu-latest
    needs: [unit-and-api-tests, prepare-artifacts]

    # Переменные окружения
    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: brutn
      DB_PASSWORD: secret_password
      DB_NAME: todo_app_test_db
      SECRET_KEY: ci_secret_key_for_jwt_testing

      # Магия вложенности Pydantic:auth__имя_переменной
      auth__JWT_PRIVATE_KEY_PATH: "certs/jwt-private-key.pem"
      auth__JWT_PUBLIC_KEY_PATH: "certs/jwt-public-key.pem"
      app__E2E_BASE_URL: "http://127.0.0.1:8000" 

    steps:
      # код на сервер GitHub через плагин
      - name: Clone code to runner
        uses: actions/checkout@v5

      # загрузка созданных раннее артефактов для работы с ними
      - name: Download generated certs and env
        uses: actions/download-artifact@v7
        with:
          name: ci-test-artifacts

        # перенос аортефактов в корень проекта
      - name: Move artifacts to root
        run: |
          cp -r ci-test-artifacts/.env ci-test-artifacts/certs .
          rm -rf ci-test-artifacts

      # Установка `uv` через их плагин
      - name: Install uv tool
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d

      # Устновка необходимых зависимостей из uv.lock / pyproject.toml
      - name: Install dependencies
        run: uv sync --all-extras --dev

      # FastAPI + Postgres в фоне через Docker Compose
      - name: Start Application Stack
        run: docker compose up -d --build

      # E2E используя подмененные переменные
      - name: Run E2E tests
        run: make test-e2e

      # Очистка томов и погашение контейнера
      - name: Stop Application Stack
        if: always() # выполнится в любом случае
        run: docker compose down -v
