name: CI Quality Gate

on:
  push:
    branches:
      - '**' # Запуск при любом пуше в любую ветку
  pull_request:
    branches: [ main ] # Запуск при создании PR в ветку main

jobs:

  # Джоб: клонирование кода, установка uv, установка зависимостей, запуск линтера (без исправлений)
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone code to runner
        uses: actions/checkout@v5

      - name: Install uv tool
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run Linter
        run: make lint

  # Джоб: подготовка окружения и ключей (артефактов)
  prepare-artifacts:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Generate dummy public JWT key for testing
        run: |
          mkdir -p certs
          openssl genpkey -algorithm RSA -out certs/jwt-private-key.pem -pkeyopt rsa_keygen_bits:2048
          openssl rsa -pubout -in certs/jwt-private-key.pem -out certs/jwt-public-key.pem
          
          # Создаем фейковый .env для Docker Compose
          echo "POSTGRES_USER=test_user" >> .env
          echo "POSTGRES_PASSWORD=test_password" >> .env
          echo "POSTGRES_DB=test_db" >> .env

      # сохранить ключи и .env как артефакты, чтобы передать в следующие job
      - name: Upload generated certs and env
        uses: actions/upload-artifact@v7
        with:
          name: ci-test-artifacts
          path: |
            certs/
            .env
          include-hidden-files:
            true
          retention-days: 1

  # Джоб: клонирование кода, загрузка артефактов, установка uv, установка зависимостей, запуск юнит и апи тестов
  unit-and-api-tests:
    runs-on: ubuntu-latest
    needs: prepare-artifacts
    steps:
      - name: Clone code to runner
        uses: actions/checkout@v5

      # загрузка созданных раннее артефактов для работы с ними
      - name: Download generated certs and env
        uses: actions/download-artifact@v7
        with:
          name: ci-test-artifacts

      - name: Install uv tool
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run unit and api tests
        run: |
          make test-crud
          make test-auth
          make test-api

  deploy:
    runs-on: ubuntu-latest
    needs: unit-and-api-tests

    if: github.ref == 'refs/heads/ci/automated-quality-gate-#8' && github.event_name == 'push'
    # if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Execute deploy commands via SSH
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{secrets.VDS_IP}}
          username: ${{secrets.VDS_USER}}
          key: ${{secrets.SSH_KEY}}
          port: 22
          script: |
            # Переход в каталог с проектом
            cd /var/www/todo-app/todo-fastapi-project

            # Защита от конфликтов: сбрасываем локальный кэш/изменения перед обновлением
            git reset --hard HEAD

            # Обновление кода из гит репозитория
            git pull origin main

            # Сборка контейнера на месте
            docker compose up -d --build

            # Удаление неиспользуемых докер-образов (старые сборки)
            docker image prune -f

  # Джоб: итоговые тесты Е2Е на целевом сервере после деплоя
  e2e_tests:
    runs-on: ubuntu-latest
    needs: deploy

    # Переменные окружения
    env:
      # Магия вложенности Pydantic:auth__имя_переменной
      app__E2E_BASE_URL: http://${{secrets.VDS_IP}}:8000 

    steps:
      # код на сервер GitHub через плагин
      - name: Clone code to runner
        uses: actions/checkout@v5

      # Установка `uv` через их плагин
      - name: Install uv tool
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d

      # Устновка необходимых зависимостей из uv.lock / pyproject.toml
      - name: Install dependencies
        run: uv sync --all-extras --dev

      # Даем вашему FastAPI на сервере 5 секунд, чтобы полностью подняться и связаться с БД
      - name: Wait for server readiness
        run: sleep 5

      - name: Run E2E tests after deploy
        run: make test_e2e
